services:
  - type: web
    name: confession-backend
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: "./confessions"
    envVars:
      - key: DB_HOST
        fromService:
	  name: confessions-db
	  property: host
      - key: DB_PORT
      	value: 5432
      - key: DB_USER
      	value: postgres
      - key: DB_PASSWORD
        value: password
      - key: DB_NAME
        value: confessions

databases:
  - name: confessions-db
    plan: free